FROM rocker/tidyverse
RUN Rscript -e "install.packages('data.table')"
RUN Rscript -e "install.packages('shinyWidgets')"
RUN Rscript -e "install.packages('shinydashboard')"
RUN Rscript -e "install.packages('leaflet')"
RUN Rscript -e "install.packages('cowplot')"
RUN Rscript -e "install.packages('rhandsontable')"

